apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-2-service
  description: Demo 2 Service
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/petarlishov/backstage-demo-1
  tags:
    - python
spec:
  type: service
  lifecycle: production
  owner: group:team-b
  system: demo-system
  dependsOn:
    - component:demo-b-sdk
    - component:demo-c-sdk
