apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-a-sdk
  description: Demo SDK A
spec:
  type: library
  lifecycle: production
  owner: group:team-a
  system: demo-system
  dependsOn:
    - component:demo-c-sdk
