apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-1-service
  description: Demo 1 Service
  tags:
    - java
relations:
  - target: component:demo-a-sdk
    type: dependsOn
  - target: resource:demo-1-db
    type: dependsOn
  - target: resource:demo-1-cache
    type: dependsOn
spec:
  type: service
  lifecycle: production
  owner: group:team-a
  system: demo-system
