apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-1-service
  description: Demo 1 Service
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: group:team-a
  system: demo-system
  providesApis:
    - demo-1-api
  dependsOn:
    - component:demo-a-sdk
    - component:demo-b-sdk
    - resource:demo-1-db
    - resource:demo-1-cache
