apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-2-service
  description: Demo 2 Service
  tags:
    - python
relations:
  - target:
      kind: component
      namespace: default
      name: demo-b-sdk
    type: dependsOn
  - target:
      kind: component
      namespace: default
      name: demo-c-sdk
    type: dependsOn
spec:
  type: service
  lifecycle: production
  owner: group:team-b
  system: demo-system
