apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-system
  description: Demo 1 system
spec:
  owner: Group:team-c


apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-1-api
  description: Damo 1 API
  tags:
    - rest
relations:
  - target: Component:demo-1-service
    type: apiProvidedBy
spec:
  type: openapi
  lifecycle: production
  owner: Group:team-a
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml


apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-1-service
  description: Demo 1 Service
  tags:
    - java
relations:
  - target: Component:demo-a-sdk
    type: dependsOn
  - target: Resource:demo-1-db
    type: dependsOn
  - target: Resource:demo-1-cache
    type: dependsOn
spec:
  type: service
  lifecycle: production
  owner: Group:team-a
  system: demo-system


apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-1-db
  description: Demo database 1
  tags:
    - mysql
spec:
  type: database
  owner: Group:team-a
  system: demo-system

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-1-cache
  description: Demo cache 1
  tags:
    - redis
spec:
  type: cache
  owner: Group:team-a
  system: demo-system




apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-2-service
  description: Demo 2 Service
  tags:
    - python
relations:
  - target: Component:demo-b-sdk
    type: dependsOn
  - target: Component:demo-c-sdk
    type: dependsOn
spec:
  type: service
  lifecycle: production
  owner: Group:team-b
  system: demo-system






apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-a-sdk
  description: Demo SDK A
relations:
  - target: Component:demo-c-sdk
    type: dependsOn
spec:
  type: library
  lifecycle: production
  owner: team-a
  system: demo-system

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-b-sdk
  description: Demo SDK B
spec:
  type: library
  lifecycle: production
  owner: Group:team-b
  system: demo-system

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-c-sdk
  description: Demo SDK C
spec:
  type: library
  lifecycle: production
  owner: Group:team-c
  system: demo-system
