apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-1-api
  description: Damo 1 API
  tags:
    - rest
relations:
  - target: component:demo-1-service
    type: apiProvidedBy
spec:
  type: openapi
  lifecycle: production
  owner: group:team-a
  definition:
    $text: https://github.com/petarlishov/backstage-demo-1/blob/main/backstage/apis/openapi.yaml
