apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-1-api
  description: Damo 1 API
  tags:
    - rest
relations:
  - target: component:demo-1-service
    type: apiProvidedBy
spec:
  type: openapi
  lifecycle: production
  owner: group:team-a
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
