apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-1-api
  description: Damo 1 API
  tags:
    - rest
relations:
  - target:
      kind: component
      name: demo-1-service
    type: apiProvidedBy
spec:
  type: openapi
  lifecycle: production
  owner: group:team-a
  definition:
    $text: ./openapi.yaml
